### ISSUE TITLE
ModuleNotFoundError: No module named 'geemap.eefolium' - geemap_app.py

### ISSUE THREAD

**Issue by Luk-kar** [giswqs/geemap-streamlit#5]
OS: Linux-Ubuntu 22.04.2

Steps followed:
1. Installed dependencies with Pipenv using the `requirements.txt` file:
   `$ pipenv install -r requirements.txt`
2. Entered the Pipenv environment:
   `$ pipenv shell`
3. Executed the Streamlit app:
   `$ streamlit run geemap_app.py`

Error encountered:
```
You can now view your Streamlit app in your browser.

  Local URL: http://localhost:9999
  Network URL: http://999.999.0.999:9999

2024-07-16 11:50:16.662 Uncaught app exception
Traceback (most recent call last):
  File "/home/dude/.local/share/virtualenvs/geemap-streamlit-ZjOHIH0S/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/home/dude//Programming/geemap.streamlit/geemap-streamlit/geemap_app.py", line 3, in <module>
    import geemap.eefolium as geemap
ModuleNotFoundError: No module named 'geemap.eefolium'
```

**Comment by Luk-kar** [comment]
The same error was when I run:
```
$ streamlit run app.py
```
